### ISSUE TITLE
support setting farmid

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tf-grid-cli#4]

**Comment by mohamedamer453** [comment]
The farm id option was added in [v1.1.1](https://github.com/threefoldtech/tf-grid-cli/releases/tag/v1.1.1)

However whenever i try it on devnet or qanet and specify a farm other than freefarm it fails with the following error.

![image](https://user-images.githubusercontent.com/101194226/226857946-ca2b37cb-a0ac-4ac9-9e9c-67d0917b4154.png)

```
mohamed@mohamed-Inspiron-3576:~$ tf-grid-cli deploy vm --name examplevm1 --ssh ~/.ssh/id_rsa.pub --farm 3
11:15AM FTL error="could not find any node with options: {Status:0xc0002c06a0 FreeMRU:0xc000374098 FreeHRU:<nil> FreeSRU:0xc0003740b0 TotalMRU:<nil> TotalHRU:<nil> TotalSRU:<nil> TotalCRU:<nil> Country:<nil> CountryContains:<nil> City:<nil> CityContains:<nil> FarmName:<nil> FarmNameContains:<nil> FarmIDs:[3] FreeIPs:0xc0003740b8 IPv4:<nil> IPv6:<nil> Domain:0xc0003740c0 Dedicated:<nil> Rentable:<nil> Rented:<nil> RentedBy:<nil> AvailableFor:<nil> NodeID:<nil> TwinID:<nil>}"
```

i'm not sure what this error means but the nodes in farm 3 qanet are working fine and both of the nodes there(4,5) are rented by my twin since this is a dedicated farm. however when i removed the farm flag and added the node flag and tried to deploy on node 4 which belongs to the same farm that i specified  i got another error mentioning that it failed to create a network because the node doesn't have a public configuration.

![image](https://user-images.githubusercontent.com/101194226/226859953-c00ad695-52f1-45fc-9481-aa7bd255122a.png)

```
mohamed@mohamed-Inspiron-3576:~$ tf-grid-cli deploy vm --name examplevm1 --ssh ~/.ssh/id_rsa.pub --node 4
11:20AM INF deploying network
11:20AM FTL error="failed to deploy network on node 4: could not generate deployments data: failed to get node 4 endpoint: no public configuration"
```

i'm not sure if the public config error is related to the one that appears when i specify the farm flag, but if it is what's causing the error, shouldn't the network be created on any other node that has public config and the deployment itself be created on the specified node/farm?

**Comment by mohamedamer453** [comment]
Verified on devnet.

I was able to use the `--farm` flag to deploy on farm 53 on devnet.

![image](https://user-images.githubusercontent.com/101194226/226916738-f10ff81c-7107-4000-b020-2348d47fe106.png)

and the `--node` flag to deploy on node 13 on devnet.

![image](https://user-images.githubusercontent.com/101194226/226917177-151ca86a-c0ad-43eb-b988-770f245cadb9.png)

And both didn't have public configs.

also worked on qanet and i was able to deploy on node `5` the same node mentioned originally in  the issue.

![image](https://user-images.githubusercontent.com/101194226/226917786-60a003b7-dc9e-4354-b1bb-33198bafff14.png)
